# -*- coding: utf-8 -*-
# @Time    : 2018-12-18 17:09
# @Author  : play4fun
# @File    : 多多进宝主题商品查询1.py
# @Software: PyCharm

"""
多多进宝主题商品查询1.py:

DdkThemeGoodsSearch
"""

from ddk.api.rest.DdkThemeGoodsSearch import DdkThemeGoodsSearch
from ddk import appinfo
import traceback, json
from config import pdd_client_id, pdd_client_secret


def test1():
    req = DdkThemeGoodsSearch()
    req.set_app_info(appinfo(pdd_client_id, secret=pdd_client_secret))
    #
    req.theme_id = 3975
    try:
        resp = req.getResponse()
        print(resp)
        print('-' * 40)
        print(json.dumps(resp))

        # print(json.dumps(f, ensure_ascii=False))
    except Exception as e:
        print(e)
        print(traceback.format_exc())
    '''
    {
    "theme_list_get_response": {
        "total": 20,
        "goods_list": [
            {
                "avg_desc": 475,
                "category_name": "男装",
                "coupon_remain_quantity": 8700,
                "avg_serv": 478,
                "avg_lgst": 479,
                "serv_pct": 0.7284,
                "promotion_rate": 200,
                "sold_quantity": 28,
                "cat_ids": [
                    239,
                    7287,
                    7319,
                    0
                ],
                "coupon_min_order_amount": 97000,
                "lgst_pct": 0.7866,
                "category_id": 743,
                "mall_id": 2265970,
                "goods_eval_score": 0,
                "cat_id": null,
                "mall_name": "俊狮服饰旗舰店",
                "coupon_total_quantity": 10000,
                "desc_pct": 0.7683,
                "merchant_type": 3,
                "goods_name": "俊狮冬季长款棉服男韩版纯色宽松连帽外套潮流加厚青年棉衣男",
                "goods_eval_count": 0,
                "goods_id": 4530990728,
                "goods_gallery_urls": null,
                "goods_desc": null,
                "opt_name": "男装",
                "goods_thumbnail_url": "http://t00img.yangkeduo.com/goods/images/2018-11-28/61255ce019a2ae43a3267cb4c04aa36b.jpeg",
                "opt_id": 743,
                "opt_ids": [
                    225,
                    3299,
                    1220,
                    1236,
                    3300,
                    743,
                    4855,
                    6359,
                    4856,
                    6360,
                    12,
                    350
                ],
                "goods_image_url": "",
                "min_normal_price": 116900,
                "has_coupon": true,
                "mall_rate": 100,
                "create_at": 1545051302,
                "min_group_price": 115900,
                "mall_cps": 1,
                "coupon_start_time": 1545062400,
                "coupon_discount": 97000,
                "coupon_end_time": 1545321599
            },
            {
                "avg_desc": 475,
                "category_name": "男装",
                "coupon_remain_quantity": 900,
                "avg_serv": 478,
                "avg_lgst": 479,
                "serv_pct": 0.7284,
                "promotion_rate": 200,
                "sold_quantity": 0,
                "cat_ids": [
                    239,
                    7287,
                    7319,
                    0
                ],
                "coupon_min_order_amount": 101000,
                "lgst_pct": 0.7866,
                "category_id": 743,
                "mall_id": 2265970,
                "goods_eval_score": null,
                "cat_id": null,
                "mall_name": "俊狮服饰旗舰店",
                "coupon_total_quantity": 1000,
                "desc_pct": 0.7683,
                "merchant_type": 3,
                "goods_name": "冬季棉服男2018新款韩版宽松棉衣工装面包服小棉袄潮流青少年外套",
                "goods_eval_count": 0,
                "goods_id": 4530975916,
                "goods_gallery_urls": null,
                "goods_desc": null,
                "opt_name": "男装",
                "goods_thumbnail_url": "http://t00img.yangkeduo.com/goods/images/2018-11-28/677ccbafdf30017be34366208b5f0eab.jpeg",
                "opt_id": 743,
                "opt_ids": [
                    225,
                    3299,
                    1220,
                    1236,
                    3300,
                    743,
                    4855,
                    6359,
                    4856,
                    6360,
                    12,
                    350
                ],
                "goods_image_url": "",
                "min_normal_price": 118900,
                "has_coupon": true,
                "mall_rate": 100,
                "create_at": 1545051357,
                "min_group_price": 117900,
                "mall_cps": 1,
                "coupon_start_time": 1544976000,
                "coupon_discount": 101000,
                "coupon_end_time": 1545321599
            },
            {
                "avg_desc": 475,
                "category_name": "男装",
                "coupon_remain_quantity": 900,
                "avg_serv": 478,
                "avg_lgst": 479,
                "serv_pct": 0.7284,
                "promotion_rate": 300,
                "sold_quantity": 0,
                "cat_ids": [
                    239,
                    7295,
                    7307,
                    0
                ],
                "coupon_min_order_amount": 39000,
                "lgst_pct": 0.7866,
                "category_id": 743,
                "mall_id": 2265970,
                "goods_eval_score": null,
                "cat_id": null,
                "mall_name": "俊狮服饰旗舰店",
                "coupon_total_quantity": 1000,
                "desc_pct": 0.7683,
                "merchant_type": 3,
                "goods_name": "俊狮秋季直筒休闲裤男2018新款ins超火的裤子潮牌宽松薄款长裤",
                "goods_eval_count": 0,
                "goods_id": 4528399892,
                "goods_gallery_urls": null,
                "goods_desc": null,
                "opt_name": "男装",
                "goods_thumbnail_url": "http://t00img.yangkeduo.com/goods/images/2018-11-28/42cb23672a495a6baae8227b71cf3a8c.jpeg",
                "opt_id": 743,
                "opt_ids": [
                    225,
                    2212,
                    743,
                    1272,
                    12,
                    350
                ],
                "goods_image_url": "",
                "min_normal_price": 48900,
                "has_coupon": true,
                "mall_rate": 100,
                "create_at": 1545051866,
                "min_group_price": 47900,
                "mall_cps": 1,
                "coupon_start_time": 1544976000,
                "coupon_discount": 39000,
                "coupon_end_time": 1545321599
            },
            {
                "avg_desc": 475,
                "category_name": "男装",
                "coupon_remain_quantity": 9800,
                "avg_serv": 478,
                "avg_lgst": 479,
                "serv_pct": 0.7284,
                "promotion_rate": 250,
                "sold_quantity": 5,
                "cat_ids": [
                    239,
                    248,
                    444,
                    0
                ],
                "coupon_min_order_amount": 34000,
                "lgst_pct": 0.7866,
                "category_id": 743,
                "mall_id": 2265970,
                "goods_eval_score": null,
                "cat_id": null,
                "mall_name": "俊狮服饰旗舰店",
                "coupon_total_quantity": 10000,
                "desc_pct": 0.7683,
                "merchant_type": 3,
                "goods_name": "俊狮秋冬毛衣男韩版圆领撞色字母套头针织衫潮牌宽松薄款外套",
                "goods_eval_count": 0,
                "goods_id": 4531422886,
                "goods_gallery_urls": null,
                "goods_desc": null,
                "opt_name": "男装",
                "goods_thumbnail_url": "http://t00img.yangkeduo.com/goods/images/2018-11-27/aaf57594496912de0c0946425920c032.jpeg",
                "opt_id": 743,
                "opt_ids": [
                    4864,
                    2592,
                    225,
                    6196,
                    743,
                    4855,
                    6187,
                    12,
                    350,
                    2590
                ],
                "goods_image_url": "",
                "min_normal_price": 42900,
                "has_coupon": true,
                "mall_rate": 100,
                "create_at": 1545052037,
                "min_group_price": 41900,
                "mall_cps": 1,
                "coupon_start_time": 1545062400,
                "coupon_discount": 34000,
                "coupon_end_time": 1545321599
            },
            {
                "avg_desc": 475,
                "category_name": "男装",
                "coupon_remain_quantity": 800,
                "avg_serv": 478,
                "avg_lgst": 479,
                "serv_pct": 0.7284,
                "promotion_rate": 200,
                "sold_quantity": 1,
                "cat_ids": [
                    239,
                    7297,
                    7322,
                    0
                ],
                "coupon_min_order_amount": 97000,
                "lgst_pct": 0.7866,
                "category_id": 743,
                "mall_id": 2265970,
                "goods_eval_score": null,
                "cat_id": null,
                "mall_name": "俊狮服饰旗舰店",
                "coupon_total_quantity": 1000,
                "desc_pct": 0.7683,
                "merchant_type": 3,
                "goods_name": "俊狮棒球羽绒服男韩版短款青年冬季保暖外套修身帅气羽绒衣服",
                "goods_eval_count": 0,
                "goods_id": 4527903318,
                "goods_gallery_urls": null,
                "goods_desc": null,
                "opt_name": "男装",
                "goods_thumbnail_url": "http://t00img.yangkeduo.com/goods/images/2018-11-28/5349a9fa3d87f608aedac344120b9e0e.jpeg",
                "opt_id": 743,
                "opt_ids": [
                    225,
                    3297,
                    3298,
                    743,
                    4855,
                    4857,
                    6361,
                    6362,
                    12,
                    350
                ],
                "goods_image_url": "",
                "min_normal_price": 114900,
                "has_coupon": true,
                "mall_rate": 100,
                "create_at": 1545051147,
                "min_group_price": 113900,
                "mall_cps": 1,
                "coupon_start_time": 1544976000,
                "coupon_discount": 97000,
                "coupon_end_time": 1545321599
            },
            {
                "avg_desc": 475,
                "category_name": "男装",
                "coupon_remain_quantity": 900,
                "avg_serv": 478,
                "avg_lgst": 479,
                "serv_pct": 0.7284,
                "promotion_rate": 200,
                "sold_quantity": 1,
                "cat_ids": [
                    239,
                    7297,
                    7322,
                    0
                ],
                "coupon_min_order_amount": 148000,
                "lgst_pct": 0.7866,
                "category_id": 743,
                "mall_id": 2265970,
                "goods_eval_score": null,
                "cat_id": null,
                "mall_name": "俊狮服饰旗舰店",
                "coupon_total_quantity": 1000,
                "desc_pct": 0.7683,
                "merchant_type": 3,
                "goods_name": "俊狮男士羽绒服2018新款韩版短款羽绒夹克冬季棒球领帅气外套",
                "goods_eval_count": 0,
                "goods_id": 4527954157,
                "goods_gallery_urls": null,
                "goods_desc": null,
                "opt_name": "男装",
                "goods_thumbnail_url": "http://t00img.yangkeduo.com/goods/images/2018-11-28/a019587a60fea3dd4be9a5717c599f9e.jpeg",
                "opt_id": 743,
                "opt_ids": [
                    225,
                    3297,
                    3298,
                    743,
                    4855,
                    4857,
                    6361,
                    6362,
                    12,
                    350
                ],
                "goods_image_url": "",
                "min_normal_price": 168900,
                "has_coupon": true,
                "mall_rate": 100,
                "create_at": 1545051203,
                "min_group_price": 167900,
                "mall_cps": 1,
                "coupon_start_time": 1544976000,
                "coupon_discount": 148000,
                "coupon_end_time": 1545321599
            },
            {
                "avg_desc": 475,
                "category_name": "男装",
                "coupon_remain_quantity": 800,
                "avg_serv": 478,
                "avg_lgst": 479,
                "serv_pct": 0.7284,
                "promotion_rate": 200,
                "sold_quantity": 2,
                "cat_ids": [
                    239,
                    7287,
                    7319,
                    0
                ],
                "coupon_min_order_amount": 90000,
                "lgst_pct": 0.7866,
                "category_id": 743,
                "mall_id": 2265970,
                "goods_eval_score": null,
                "cat_id": null,
                "mall_name": "俊狮服饰旗舰店",
                "coupon_total_quantity": 1000,
                "desc_pct": 0.7683,
                "merchant_type": 3,
                "goods_name": "俊狮冬季棉衣男装韩版潮流帅气冬天衣服保暖外套修身棉服男",
                "goods_eval_count": 0,
                "goods_id": 4530982755,
                "goods_gallery_urls": null,
                "goods_desc": null,
                "opt_name": "男装",
                "goods_thumbnail_url": "http://t00img.yangkeduo.com/goods/images/2018-11-28/dc87b298c97cc6849e37d78799d83734.jpeg",
                "opt_id": 743,
                "opt_ids": [
                    225,
                    3299,
                    1220,
                    1236,
                    3300,
                    743,
                    4855,
                    6359,
                    4856,
                    6360,
                    12,
                    350
                ],
                "goods_image_url": "",
                "min_normal_price": 108900,
                "has_coupon": true,
                "mall_rate": 100,
                "create_at": 1545051255,
                "min_group_price": 107900,
                "mall_cps": 1,
                "coupon_start_time": 1544976000,
                "coupon_discount": 90000,
                "coupon_end_time": 1545321599
            },
            {
                "avg_desc": 475,
                "category_name": "男装",
                "coupon_remain_quantity": 500,
                "avg_serv": 478,
                "avg_lgst": 479,
                "serv_pct": 0.7284,
                "promotion_rate": 200,
                "sold_quantity": 5,
                "cat_ids": [
                    239,
                    7287,
                    7319,
                    0
                ],
                "coupon_min_order_amount": 96000,
                "lgst_pct": 0.7866,
                "category_id": 743,
                "mall_id": 2265970,
                "goods_eval_score": null,
                "cat_id": null,
                "mall_name": "俊狮服饰旗舰店",
                "coupon_total_quantity": 1000,
                "desc_pct": 0.7683,
                "merchant_type": 3,
                "goods_name": "俊狮冬装网红棉服男短款青年帅气休闲棉袄修身棒球服潮牌夹克",
                "goods_eval_count": 0,
                "goods_id": 4530974928,
                "goods_gallery_urls": null,
                "goods_desc": null,
                "opt_name": "男装",
                "goods_thumbnail_url": "http://t00img.yangkeduo.com/goods/images/2018-11-28/4f341eb805389e06fcd2463a32c13479.jpeg",
                "opt_id": 743,
                "opt_ids": [
                    225,
                    3299,
                    1220,
                    1236,
                    3300,
                    743,
                    4855,
                    6359,
                    4856,
                    6360,
                    12,
                    350
                ],
                "goods_image_url": "",
                "min_normal_price": 116900,
                "has_coupon": true,
                "mall_rate": 100,
                "create_at": 1545051410,
                "min_group_price": 115900,
                "mall_cps": 1,
                "coupon_start_time": 1544976000,
                "coupon_discount": 96000,
                "coupon_end_time": 1545321599
            },
            {
                "avg_desc": 475,
                "category_name": "男装",
                "coupon_remain_quantity": 900,
                "avg_serv": 478,
                "avg_lgst": 479,
                "serv_pct": 0.7284,
                "promotion_rate": 200,
                "sold_quantity": 1,
                "cat_ids": [
                    239,
                    7287,
                    7319,
                    0
                ],
                "coupon_min_order_amount": 115000,
                "lgst_pct": 0.7866,
                "category_id": 743,
                "mall_id": 2265970,
                "goods_eval_score": null,
                "cat_id": null,
                "mall_name": "俊狮服饰旗舰店",
                "coupon_total_quantity": 1000,
                "desc_pct": 0.7683,
                "merchant_type": 3,
                "goods_name": "俊狮短款男棉衣潮流修身男外套袄子2018新款韩版帅气修身棉服",
                "goods_eval_count": 0,
                "goods_id": 4551597335,
                "goods_gallery_urls": null,
                "goods_desc": null,
                "opt_name": "男装",
                "goods_thumbnail_url": "http://t00img.yangkeduo.com/goods/images/2018-11-28/64cf167a31168c0947669d4ee5babc59.jpeg",
                "opt_id": 743,
                "opt_ids": [
                    225,
                    3299,
                    1220,
                    1236,
                    3300,
                    743,
                    4855,
                    6359,
                    4856,
                    6360,
                    12,
                    350
                ],
                "goods_image_url": "",
                "min_normal_price": 130900,
                "has_coupon": true,
                "mall_rate": 100,
                "create_at": 1545051469,
                "min_group_price": 129900,
                "mall_cps": 1,
                "coupon_start_time": 1544976000,
                "coupon_discount": 115000,
                "coupon_end_time": 1545321599
            },
            {
                "avg_desc": 475,
                "category_name": "男装",
                "coupon_remain_quantity": 900,
                "avg_serv": 478,
                "avg_lgst": 479,
                "serv_pct": 0.7284,
                "promotion_rate": 200,
                "sold_quantity": 0,
                "cat_ids": [
                    239,
                    7287,
                    7319,
                    0
                ],
                "coupon_min_order_amount": 120000,
                "lgst_pct": 0.7866,
                "category_id": 743,
                "mall_id": 2265970,
                "goods_eval_score": null,
                "cat_id": null,
                "mall_name": "俊狮服饰旗舰店",
                "coupon_total_quantity": 1000,
                "desc_pct": 0.7683,
                "merchant_type": 3,
                "goods_name": "no1dara冬装外套男棉服韩版棉衣男装加绒加厚短款爸爸装中年棉袄",
                "goods_eval_count": 0,
                "goods_id": 4531071382,
                "goods_gallery_urls": null,
                "goods_desc": null,
                "opt_name": "男装",
                "goods_thumbnail_url": "http://t00img.yangkeduo.com/goods/images/2018-11-27/2d5a66ba12c2df3c07ac6bff764a7b38.jpeg",
                "opt_id": 743,
                "opt_ids": [
                    225,
                    3299,
                    1220,
                    1236,
                    3300,
                    743,
                    4855,
                    6359,
                    4856,
                    6360,
                    12,
                    350
                ],
                "goods_image_url": "http://t00img.yangkeduo.com/openapi/images/2018-11-27/7f9d4e8e5448272eed150f9366decfcb.jpeg",
                "min_normal_price": 140900,
                "has_coupon": true,
                "mall_rate": 100,
                "create_at": 1545051523,
                "min_group_price": 139900,
                "mall_cps": 1,
                "coupon_start_time": 1544976000,
                "coupon_discount": 120000,
                "coupon_end_time": 1545321599
            },
            {
                "avg_desc": 475,
                "category_name": "男装",
                "coupon_remain_quantity": 800,
                "avg_serv": 478,
                "avg_lgst": 479,
                "serv_pct": 0.7284,
                "promotion_rate": 200,
                "sold_quantity": 4,
                "cat_ids": [
                    239,
                    7287,
                    7319,
                    0
                ],
                "coupon_min_order_amount": 87000,
                "lgst_pct": 0.7866,
                "category_id": 743,
                "mall_id": 2265970,
                "goods_eval_score": null,
                "cat_id": null,
                "mall_name": "俊狮服饰旗舰店",
                "coupon_total_quantity": 1000,
                "desc_pct": 0.7683,
                "merchant_type": 3,
                "goods_name": "男士外套冬季2017新款羽绒男装棉衣韩版修身潮流棉服帅气加厚棉袄",
                "goods_eval_count": 0,
                "goods_id": 4531083240,
                "goods_gallery_urls": null,
                "goods_desc": null,
                "opt_name": "男装",
                "goods_thumbnail_url": "http://t00img.yangkeduo.com/goods/images/2018-11-27/1e7e93f171df8161db15a7c1a2d23e42.jpeg",
                "opt_id": 743,
                "opt_ids": [
                    225,
                    3299,
                    1220,
                    1236,
                    3300,
                    743,
                    4855,
                    6359,
                    4856,
                    6360,
                    12,
                    350
                ],
                "goods_image_url": "http://t00img.yangkeduo.com/openapi/images/2018-11-27/fa84ef47fe9b2d331c84a0f0422b1c28.jpeg",
                "min_normal_price": 106900,
                "has_coupon": true,
                "mall_rate": 100,
                "create_at": 1545051570,
                "min_group_price": 105900,
                "mall_cps": 1,
                "coupon_start_time": 1544976000,
                "coupon_discount": 87000,
                "coupon_end_time": 1545321599
            },
            {
                "avg_desc": 475,
                "category_name": "男装",
                "coupon_remain_quantity": 900,
                "avg_serv": 478,
                "avg_lgst": 479,
                "serv_pct": 0.7284,
                "promotion_rate": 200,
                "sold_quantity": 1,
                "cat_ids": [
                    239,
                    7287,
                    7319,
                    0
                ],
                "coupon_min_order_amount": 85000,
                "lgst_pct": 0.7866,
                "category_id": 743,
                "mall_id": 2265970,
                "goods_eval_score": null,
                "cat_id": null,
                "mall_name": "俊狮服饰旗舰店",
                "coupon_total_quantity": 1000,
                "desc_pct": 0.7683,
                "merchant_type": 3,
                "goods_name": "保暖背心潮流男士棉马甲男秋冬季韩版坎肩帅气修身羽绒棉外套男",
                "goods_eval_count": 0,
                "goods_id": 4531097001,
                "goods_gallery_urls": null,
                "goods_desc": null,
                "opt_name": "男装",
                "goods_thumbnail_url": "http://t00img.yangkeduo.com/goods/images/2018-11-27/3ba7b7d8ca2e3a64dd3c0ff894fda158.jpeg",
                "opt_id": 743,
                "opt_ids": [
                    225,
                    3299,
                    1220,
                    1236,
                    3300,
                    743,
                    4855,
                    6359,
                    4856,
                    6360,
                    12,
                    350
                ],
                "goods_image_url": "http://t00img.yangkeduo.com/openapi/images/2018-11-27/ac740a93931b576dce062cf7d4fe05ff.jpeg",
                "min_normal_price": 102900,
                "has_coupon": true,
                "mall_rate": 100,
                "create_at": 1545051613,
                "min_group_price": 101900,
                "mall_cps": 1,
                "coupon_start_time": 1544976000,
                "coupon_discount": 85000,
                "coupon_end_time": 1545321599
            },
            {
                "avg_desc": 475,
                "category_name": "男装",
                "coupon_remain_quantity": 900,
                "avg_serv": 478,
                "avg_lgst": 479,
                "serv_pct": 0.7284,
                "promotion_rate": 250,
                "sold_quantity": 0,
                "cat_ids": [
                    239,
                    7295,
                    7307,
                    0
                ],
                "coupon_min_order_amount": 40000,
                "lgst_pct": 0.7866,
                "category_id": 743,
                "mall_id": 2265970,
                "goods_eval_score": null,
                "cat_id": null,
                "mall_name": "俊狮服饰旗舰店",
                "coupon_total_quantity": 1000,
                "desc_pct": 0.7683,
                "merchant_type": 3,
                "goods_name": "俊狮韩版休闲裤男潮流三条杠运动裤宽松百搭卫裤直筒网红裤子",
                "goods_eval_count": 0,
                "goods_id": 4528339426,
                "goods_gallery_urls": null,
                "goods_desc": null,
                "opt_name": "男装",
                "goods_thumbnail_url": "http://t00img.yangkeduo.com/goods/images/2018-11-28/acc8156a65a75e7e597b86a5f230522d.jpeg",
                "opt_id": 743,
                "opt_ids": [
                    225,
                    2212,
                    743,
                    1272,
                    12,
                    350
                ],
                "goods_image_url": "",
                "min_normal_price": 48900,
                "has_coupon": true,
                "mall_rate": 100,
                "create_at": 1545051660,
                "min_group_price": 47900,
                "mall_cps": 1,
                "coupon_start_time": 1544976000,
                "coupon_discount": 40000,
                "coupon_end_time": 1545321599
            },
            {
                "avg_desc": 475,
                "category_name": "男装",
                "coupon_remain_quantity": 300,
                "avg_serv": 478,
                "avg_lgst": 479,
                "serv_pct": 0.7284,
                "promotion_rate": 250,
                "sold_quantity": 16,
                "cat_ids": [
                    239,
                    7295,
                    7307,
                    0
                ],
                "coupon_min_order_amount": 41000,
                "lgst_pct": 0.7866,
                "category_id": 743,
                "mall_id": 2265970,
                "goods_eval_score": 0,
                "cat_id": null,
                "mall_name": "俊狮服饰旗舰店",
                "coupon_total_quantity": 1000,
                "desc_pct": 0.7683,
                "merchant_type": 3,
                "goods_name": "俊狮2018加绒束脚裤男冬季韩版休闲裤潮流网红运动长裤子套装",
                "goods_eval_count": 0,
                "goods_id": 4528335369,
                "goods_gallery_urls": null,
                "goods_desc": null,
                "opt_name": "男装",
                "goods_thumbnail_url": "http://t00img.yangkeduo.com/goods/images/2018-11-28/f15ce6468c436885143baa3f4e68ea50.jpeg",
                "opt_id": 743,
                "opt_ids": [
                    225,
                    2212,
                    743,
                    1272,
                    12,
                    350
                ],
                "goods_image_url": "",
                "min_normal_price": 50900,
                "has_coupon": true,
                "mall_rate": 100,
                "create_at": 1545051705,
                "min_group_price": 49900,
                "mall_cps": 1,
                "coupon_start_time": 1544976000,
                "coupon_discount": 41000,
                "coupon_end_time": 1545321599
            },
            {
                "avg_desc": 475,
                "category_name": "男装",
                "coupon_remain_quantity": 900,
                "avg_serv": 478,
                "avg_lgst": 479,
                "serv_pct": 0.7284,
                "promotion_rate": 250,
                "sold_quantity": 0,
                "cat_ids": [
                    239,
                    7295,
                    7307,
                    0
                ],
                "coupon_min_order_amount": 46000,
                "lgst_pct": 0.7866,
                "category_id": 743,
                "mall_id": 2265970,
                "goods_eval_score": null,
                "cat_id": null,
                "mall_name": "俊狮服饰旗舰店",
                "coupon_total_quantity": 1000,
                "desc_pct": 0.7683,
                "merchant_type": 3,
                "goods_name": "俊狮男裤2018秋季新款韩版时尚男士裤子潮流修身系带休闲裤",
                "goods_eval_count": 0,
                "goods_id": 4528361744,
                "goods_gallery_urls": null,
                "goods_desc": null,
                "opt_name": "男装",
                "goods_thumbnail_url": "http://t00img.yangkeduo.com/goods/images/2018-11-28/5f61ab203d8274e6d51dce34ccae753a.jpeg",
                "opt_id": 743,
                "opt_ids": [
                    225,
                    2212,
                    743,
                    1272,
                    12,
                    350
                ],
                "goods_image_url": "",
                "min_normal_price": 54900,
                "has_coupon": true,
                "mall_rate": 100,
                "create_at": 1545051751,
                "min_group_price": 53900,
                "mall_cps": 1,
                "coupon_start_time": 1544976000,
                "coupon_discount": 46000,
                "coupon_end_time": 1545321599
            },
            {
                "avg_desc": 475,
                "category_name": "男装",
                "coupon_remain_quantity": 900,
                "avg_serv": 478,
                "avg_lgst": 479,
                "serv_pct": 0.7284,
                "promotion_rate": 200,
                "sold_quantity": 0,
                "cat_ids": [
                    239,
                    7295,
                    7307,
                    0
                ],
                "coupon_min_order_amount": 61000,
                "lgst_pct": 0.7866,
                "category_id": 743,
                "mall_id": 2265970,
                "goods_eval_score": null,
                "cat_id": null,
                "mall_name": "俊狮服饰旗舰店",
                "coupon_total_quantity": 1000,
                "desc_pct": 0.7683,
                "merchant_type": 3,
                "goods_name": "俊狮秋季休闲裤男韩版新款撞色拼接束脚运动裤潮牌宽松长裤子",
                "goods_eval_count": 0,
                "goods_id": 4528355780,
                "goods_gallery_urls": null,
                "goods_desc": null,
                "opt_name": "男装",
                "goods_thumbnail_url": "http://t00img.yangkeduo.com/goods/images/2018-11-28/8178063823933edef41b0297f193ebd9.jpeg",
                "opt_id": 743,
                "opt_ids": [
                    225,
                    2212,
                    743,
                    1272,
                    12,
                    350
                ],
                "goods_image_url": "",
                "min_normal_price": 70900,
                "has_coupon": true,
                "mall_rate": 100,
                "create_at": 1545052367,
                "min_group_price": 69900,
                "mall_cps": 1,
                "coupon_start_time": 1544976000,
                "coupon_discount": 61000,
                "coupon_end_time": 1545321599
            },
            {
                "avg_desc": 475,
                "category_name": "男装",
                "coupon_remain_quantity": 900,
                "avg_serv": 478,
                "avg_lgst": 479,
                "serv_pct": 0.7284,
                "promotion_rate": 200,
                "sold_quantity": 1,
                "cat_ids": [
                    239,
                    248,
                    444,
                    0
                ],
                "coupon_min_order_amount": 46000,
                "lgst_pct": 0.7866,
                "category_id": 743,
                "mall_id": 2265970,
                "goods_eval_score": null,
                "cat_id": null,
                "mall_name": "俊狮服饰旗舰店",
                "coupon_total_quantity": 1000,
                "desc_pct": 0.7683,
                "merchant_type": 3,
                "goods_name": "俊狮针织衫男秋季2018新款休闲白色毛衣韩版套头中领加厚线衫",
                "goods_eval_count": 0,
                "goods_id": 4531353766,
                "goods_gallery_urls": null,
                "goods_desc": null,
                "opt_name": "男装",
                "goods_thumbnail_url": "http://t00img.yangkeduo.com/goods/images/2018-11-27/851721008d8ab6f4fbc76ad20df7fc4c.jpeg",
                "opt_id": 743,
                "opt_ids": [
                    4864,
                    2592,
                    225,
                    6196,
                    743,
                    4855,
                    6187,
                    12,
                    350,
                    2590
                ],
                "goods_image_url": "",
                "min_normal_price": 54900,
                "has_coupon": true,
                "mall_rate": 100,
                "create_at": 1545051922,
                "min_group_price": 53900,
                "mall_cps": 1,
                "coupon_start_time": 1544976000,
                "coupon_discount": 46000,
                "coupon_end_time": 1545321599
            },
            {
                "avg_desc": 475,
                "category_name": "男装",
                "coupon_remain_quantity": 900,
                "avg_serv": 478,
                "avg_lgst": 479,
                "serv_pct": 0.7284,
                "promotion_rate": 250,
                "sold_quantity": 0,
                "cat_ids": [
                    239,
                    248,
                    444,
                    0
                ],
                "coupon_min_order_amount": 43000,
                "lgst_pct": 0.7866,
                "category_id": 743,
                "mall_id": 2265970,
                "goods_eval_score": null,
                "cat_id": null,
                "mall_name": "俊狮服饰旗舰店",
                "coupon_total_quantity": 1000,
                "desc_pct": 0.7683,
                "merchant_type": 3,
                "goods_name": "俊狮高领毛衣男冬季修身韩版毛衫帅气青少年潮流学生款针织衫",
                "goods_eval_count": 0,
                "goods_id": 4531396672,
                "goods_gallery_urls": null,
                "goods_desc": null,
                "opt_name": "男装",
                "goods_thumbnail_url": "http://t00img.yangkeduo.com/goods/images/2018-11-27/227804a92b48bdfcf2ff4e2c91483ee7.jpeg",
                "opt_id": 743,
                "opt_ids": [
                    4864,
                    2592,
                    225,
                    6196,
                    743,
                    4855,
                    6187,
                    12,
                    350,
                    2590
                ],
                "goods_image_url": "",
                "min_normal_price": 52900,
                "has_coupon": true,
                "mall_rate": 100,
                "create_at": 1545051970,
                "min_group_price": 51900,
                "mall_cps": 1,
                "coupon_start_time": 1544976000,
                "coupon_discount": 43000,
                "coupon_end_time": 1545321599
            },
            {
                "avg_desc": 475,
                "category_name": "男装",
                "coupon_remain_quantity": 900,
                "avg_serv": 478,
                "avg_lgst": 479,
                "serv_pct": 0.7284,
                "promotion_rate": 200,
                "sold_quantity": 1,
                "cat_ids": [
                    239,
                    248,
                    444,
                    0
                ],
                "coupon_min_order_amount": 43000,
                "lgst_pct": 0.7866,
                "category_id": 743,
                "mall_id": 2265970,
                "goods_eval_score": null,
                "cat_id": null,
                "mall_name": "俊狮服饰旗舰店",
                "coupon_total_quantity": 1000,
                "desc_pct": 0.7683,
                "merchant_type": 3,
                "goods_name": "毛衣男冬季2018新款韩版圆领加厚毛衫潮流线衫学生慵懒风男针织衫",
                "goods_eval_count": 0,
                "goods_id": 4531401639,
                "goods_gallery_urls": null,
                "goods_desc": null,
                "opt_name": "男装",
                "goods_thumbnail_url": "http://t00img.yangkeduo.com/goods/images/2018-11-27/5035b72a8a574f71e1a6f9c5d06bbbaf.jpeg",
                "opt_id": 743,
                "opt_ids": [
                    4864,
                    2592,
                    225,
                    6196,
                    743,
                    4855,
                    6187,
                    12,
                    350,
                    2590
                ],
                "goods_image_url": "",
                "min_normal_price": 50900,
                "has_coupon": true,
                "mall_rate": 100,
                "create_at": 1545052416,
                "min_group_price": 49900,
                "mall_cps": 1,
                "coupon_start_time": 1544976000,
                "coupon_discount": 43000,
                "coupon_end_time": 1545321599
            },
            {
                "avg_desc": 475,
                "category_name": "男装",
                "coupon_remain_quantity": 900,
                "avg_serv": 478,
                "avg_lgst": 479,
                "serv_pct": 0.7284,
                "promotion_rate": 250,
                "sold_quantity": 0,
                "cat_ids": [
                    239,
                    248,
                    444,
                    0
                ],
                "coupon_min_order_amount": 41000,
                "lgst_pct": 0.7866,
                "category_id": 743,
                "mall_id": 2265970,
                "goods_eval_score": null,
                "cat_id": null,
                "mall_name": "俊狮服饰旗舰店",
                "coupon_total_quantity": 1000,
                "desc_pct": 0.7683,
                "merchant_type": 3,
                "goods_name": "俊狮黑色毛衣男秋冬韩版假两件修身线衫圆领线衣潮牌薄款外套",
                "goods_eval_count": 0,
                "goods_id": 4531467762,
                "goods_gallery_urls": null,
                "goods_desc": null,
                "opt_name": "男装",
                "goods_thumbnail_url": "http://t00img.yangkeduo.com/goods/images/2018-11-27/f179258814bf01c15ec9e5dd5f2de282.jpeg",
                "opt_id": 743,
                "opt_ids": [
                    4864,
                    2592,
                    225,
                    6196,
                    743,
                    4855,
                    6187,
                    12,
                    350,
                    2590
                ],
                "goods_image_url": "",
                "min_normal_price": 50900,
                "has_coupon": true,
                "mall_rate": 100,
                "create_at": 1545052083,
                "min_group_price": 49900,
                "mall_cps": 1,
                "coupon_start_time": 1544976000,
                "coupon_discount": 41000,
                "coupon_end_time": 1545321599
            }
        ],
        "request_id": "15451260721836886"
    }
}
    '''

if __name__ == '__main__':
    test1()
